const calendarRoot = document.querySelector('[data-crm-calendar]');

if (calendarRoot) {
    const state = { month: new Date().toISOString().slice(0, 7), events: [] };
    const base = calendarRoot.dataset.apiBase;
    const dialog = calendarRoot.querySelector('[data-calendar-dialog]');
    const form = calendarRoot.querySelector('[data-calendar-form]');
    const escapeHtml = (value) => String(value ?? '').replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[character]);
    const localDateTime = (value) => value ? new Date(value).toLocaleString('sv-SE').slice(0, 16).replace(' ', 'T') : '';
    const showState = (name) => calendarRoot.querySelectorAll('[data-calendar-state]').forEach((element) => element.classList.toggle('hidden', element.dataset.calendarState !== name));
    const feedback = (message, tone = 'success') => { const target = calendarRoot.querySelector('[data-calendar-feedback]'); target.className = `mt-4 rounded-lg p-3 text-sm ${tone === 'error' ? 'bg-red-50 text-red-700' : 'bg-emerald-50 text-emerald-700'}`; target.textContent = message; target.classList.remove('hidden'); };
    const errorMessage = (payload) => Object.values(payload?.errors || {}).flat()[0] || payload?.message || 'Verifique os dados e tente novamente.';
    const formatDate = (value, allDay) => new Intl.DateTimeFormat('pt-BR', allDay ? { dateStyle: 'full' } : { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value));
    const range = () => { const [year, month] = state.month.split('-').map(Number); return { from: `${state.month}-01`, to: new Date(Date.UTC(year, month, 0, 23, 59, 59)).toISOString().slice(0, 19) }; };
    const resetForm = () => { form.reset(); delete form.dataset.eventId; calendarRoot.querySelector('[data-calendar-form-title]').textContent = 'Adicionar evento'; calendarRoot.querySelector('[data-calendar-submit]').textContent = 'Salvar evento'; };
    const openCreate = () => { resetForm(); dialog.showModal(); };
    const openEdit = (id) => { const event = state.events.find((item) => String(item.id) === String(id)); if (!event) return; form.dataset.eventId = id; form.elements.title.value = event.title || ''; form.elements.start_at.value = localDateTime(event.start_at); form.elements.end_at.value = localDateTime(event.end_at); form.elements.all_day.checked = Boolean(event.all_day); form.elements.notes.value = event.notes || ''; calendarRoot.querySelector('[data-calendar-form-title]').textContent = 'Editar evento'; calendarRoot.querySelector('[data-calendar-submit]').textContent = 'Salvar alterações'; dialog.showModal(); };
    const load = async () => { showState('loading'); try { const period = range(); const response = await fetch(`${base}/calendar-events?from=${encodeURIComponent(period.from)}&to=${encodeURIComponent(period.to)}&per_page=100`); const payload = await response.json(); if (!response.ok) throw new Error(errorMessage(payload)); state.events = payload.data || []; calendarRoot.querySelector('[data-calendar-events]').innerHTML = state.events.length ? state.events.map((event) => `<article class="flex flex-col gap-3 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="font-semibold text-slate-800">${escapeHtml(event.title)}</h2><p class="mt-1 text-sm text-slate-500">${formatDate(event.start_at, event.all_day)}${event.all_day ? '' : ` até ${formatDate(event.end_at, false)}`}</p>${event.notes ? `<p class="mt-2 text-sm text-slate-600">${escapeHtml(event.notes)}</p>` : ''}</div><div class="flex flex-wrap gap-2"><button type="button" data-edit-event="${event.id}" class="rounded-lg border border-slate-200 px-3 py-2 text-sm font-bold text-slate-600 hover:bg-slate-50">Editar</button><button type="button" data-cancel-event="${event.id}" class="rounded-lg border border-slate-200 px-3 py-2 text-sm font-bold text-slate-600 hover:border-red-300 hover:bg-red-50 hover:text-red-700">Cancelar</button></div></article>`).join('') : '<div class="px-5 py-14 text-center text-slate-500">Nenhum evento agendado para este mês.</div>'; calendarRoot.querySelectorAll('[data-cancel-event]').forEach((button) => button.addEventListener('click', () => cancelEvent(button))); calendarRoot.querySelectorAll('[data-edit-event]').forEach((button) => button.addEventListener('click', () => openEdit(button.dataset.editEvent))); showState('content'); } catch (error) { calendarRoot.querySelector('[data-calendar-error]').textContent = error.message; showState('error'); } };
    const cancelEvent = async (button) => { if (!confirm('Cancelar este evento?')) return; button.disabled = true; try { const response = await fetch(`${base}/calendar-events/${button.dataset.cancelEvent}`, { method: 'DELETE', headers: { Accept: 'application/json' } }); if (!response.ok) throw new Error(errorMessage(await response.json())); feedback('Evento cancelado.'); await load(); } catch (error) { feedback(error.message, 'error'); button.disabled = false; } };
    calendarRoot.querySelector('[data-calendar-month]').value = state.month;
    calendarRoot.querySelector('[data-calendar-month]').addEventListener('change', (event) => { state.month = event.target.value; load(); });
    calendarRoot.querySelector('[data-calendar-retry]').addEventListener('click', load);
    calendarRoot.querySelector('[data-calendar-open-form]').addEventListener('click', openCreate);
    calendarRoot.querySelectorAll('[data-calendar-close]').forEach((button) => button.addEventListener('click', () => dialog.close()));
    form.addEventListener('submit', async (event) => { event.preventDefault(); const submit = form.querySelector('[data-calendar-submit]'); submit.disabled = true; calendarRoot.querySelector('[data-calendar-form-error]').classList.add('hidden'); try { const data = Object.fromEntries(new FormData(form)); data.start_at = new Date(data.start_at).toISOString(); data.end_at = new Date(data.end_at).toISOString(); data.all_day = form.elements.all_day.checked; data.timezone = Intl.DateTimeFormat().resolvedOptions().timeZone; const id = form.dataset.eventId; const response = await fetch(id ? `${base}/calendar-events/${id}` : `${base}/calendar-events`, { method: id ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json', Accept: 'application/json' }, body: JSON.stringify(data) }); const payload = await response.json(); if (!response.ok) throw new Error(errorMessage(payload)); resetForm(); dialog.close(); feedback(id ? 'Evento atualizado com sucesso.' : 'Evento criado com sucesso.'); await load(); } catch (error) { const target = calendarRoot.querySelector('[data-calendar-form-error]'); target.textContent = error.message; target.classList.remove('hidden'); } finally { submit.disabled = false; } });
    load();
}
