const inboxRoot = document.querySelector('[data-crm-inbox]');
if (inboxRoot) {
    const state = { conversations: [], selected: null };
    const base = inboxRoot.dataset.apiBase;
    const escapeHtml = (value) => String(value ?? '').replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[character]);
    const feedback = (message, tone = 'success') => { const target = inboxRoot.querySelector('[data-inbox-feedback]'); target.className = `mt-8 rounded-lg p-3 text-sm ${tone === 'error' ? 'bg-red-50 text-red-700' : 'bg-emerald-50 text-emerald-700'}`; target.textContent = message; target.classList.remove('hidden'); };
    const showDetail = (conversation) => { state.selected = conversation; inboxRoot.querySelector('[data-inbox-detail]').innerHTML = `<div class="flex items-start justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-[0.12em] text-accent-600">${escapeHtml(conversation.channel || 'Canal')}</p><h2 class="mt-1 text-xl font-bold text-slate-900">Conversa #${conversation.id}</h2></div><span class="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-600">${escapeHtml(conversation.status || 'aberta')}</span></div><div class="mt-6 space-y-3">${(conversation.messages || []).length ? conversation.messages.map((message) => `<article class="rounded-xl ${message.direction === 'internal' ? 'bg-amber-50' : 'bg-slate-50'} p-4"><p class="text-xs font-bold uppercase tracking-[0.1em] text-slate-500">${escapeHtml(message.direction || 'mensagem')}</p><p class="mt-2 whitespace-pre-wrap text-sm text-slate-700">${escapeHtml(message.body || '')}</p></article>`).join('') : '<p class="text-sm text-slate-500">Nenhuma mensagem registrada.</p>'}</div>`; inboxRoot.querySelector('[data-inbox-message-form]').classList.remove('hidden'); };
    const loadConversation = async (id) => { try { const response = await fetch(`${base}/conversations/${id}`); const payload = await response.json(); if (!response.ok) throw new Error(payload.message || 'Não foi possível abrir a conversa.'); showDetail(payload.data || payload); } catch (error) { feedback(error.message, 'error'); } };
    const load = async () => { try { const response = await fetch(`${base}/conversations?per_page=50`); const payload = await response.json(); if (!response.ok) throw new Error(payload.message || 'Não foi possível carregar as conversas.'); state.conversations = payload.data || []; inboxRoot.querySelector('[data-inbox-list-state]').classList.add('hidden'); const list = inboxRoot.querySelector('[data-inbox-list]'); list.innerHTML = state.conversations.length ? state.conversations.map((conversation) => `<button type="button" data-conversation-id="${conversation.id}" class="block w-full px-5 py-4 text-left hover:bg-brand-50"><span class="text-xs font-bold uppercase tracking-[0.1em] text-accent-600">${escapeHtml(conversation.channel || 'canal')}</span><strong class="mt-1 block text-sm text-slate-800">Conversa #${conversation.id}</strong><span class="mt-1 block text-xs text-slate-500">${conversation.unread_messages_count || 0} não lidas</span></button>`).join('') : '<p class="p-5 text-sm text-slate-500">Nenhuma conversa disponível.</p>'; list.classList.remove('hidden'); list.querySelectorAll('[data-conversation-id]').forEach((button) => button.addEventListener('click', () => loadConversation(button.dataset.conversationId))); } catch (error) { inboxRoot.querySelector('[data-inbox-list-state]').textContent = error.message; feedback(error.message, 'error'); } };
    inboxRoot.querySelector('[data-inbox-message-form]').addEventListener('submit', async (event) => { event.preventDefault(); if (!state.selected) return; const form = event.currentTarget; const body = new FormData(form).get('body'); try { const response = await fetch(`${base}/conversations/${state.selected.id}/messages`, { method: 'POST', headers: { 'Content-Type': 'application/json', Accept: 'application/json' }, body: JSON.stringify({ direction: 'internal', body, idempotency_key: crypto.randomUUID() }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.message || 'Não foi possível enviar a nota.'); form.reset(); feedback('Nota interna registrada.'); await loadConversation(state.selected.id); } catch (error) { feedback(error.message, 'error'); } });
    load();
}
