const resourceRoot = document.querySelector('[data-crm-resource]');
if (resourceRoot) {
    const resource = resourceRoot.dataset.resource;
    const endpoint = resource === 'campaigns' ? 'email-campaigns' : 'automations';
    const dialog = resourceRoot.querySelector('[data-resource-dialog]');
    const form = resourceRoot.querySelector('[data-resource-form]');
    const escapeHtml = (value) => String(value ?? '').replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[character]);
    const show = (name) => resourceRoot.querySelectorAll('[data-resource-state]').forEach((element) => element.classList.toggle('hidden', element.dataset.resourceState !== name));
    const feedback = (message, tone = 'success') => { const target = resourceRoot.querySelector('[data-resource-feedback]'); target.className = `mt-8 rounded-lg p-3 text-sm ${tone === 'error' ? 'bg-red-50 text-red-700' : 'bg-emerald-50 text-emerald-700'}`; target.textContent = message; target.classList.remove('hidden'); };
    const load = async () => { show('loading'); try { const response = await fetch(`${resourceRoot.dataset.apiBase}/${endpoint}`); const payload = await response.json(); if (!response.ok) throw new Error(payload.message || 'Falha ao carregar registros.'); const rows = payload.data || []; resourceRoot.querySelector('[data-resource-rows]').innerHTML = rows.length ? rows.map((row) => `<article class="flex flex-col gap-2 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="font-semibold text-slate-800">${escapeHtml(row.name || row.title || `Registro #${row.id}`)}</h2><p class="text-sm text-slate-500">${escapeHtml(row.status || (row.active === false ? 'inativo' : 'ativo'))}</p></div>${resource === 'campaigns' && ['draft', 'scheduled'].includes(row.status) ? `<button type="button" data-send-campaign="${row.id}" class="rounded-lg border border-slate-200 px-3 py-2 text-sm font-bold text-slate-700">Enviar</button>` : ''}</article>`).join('') : '<p class="px-5 py-14 text-center text-slate-500">Nenhum registro encontrado.</p>'; resourceRoot.querySelectorAll('[data-send-campaign]').forEach((button) => button.addEventListener('click', () => sendCampaign(button))); show('content'); } catch (error) { resourceRoot.querySelector('[data-resource-error]').textContent = error.message; show('error'); } };
    const sendCampaign = async (button) => { if (!window.confirm('Enviar esta campanha agora?')) return; const response = await fetch(`${resourceRoot.dataset.apiBase}/email-campaigns/${button.dataset.sendCampaign}/send`, { method: 'POST', headers: { Accept: 'application/json' } }); const payload = await response.json(); if (!response.ok) feedback(payload.message || 'Não foi possível enviar.', 'error'); else { feedback('Campanha enviada.'); load(); } };
    resourceRoot.querySelector('[data-resource-open-form]').addEventListener('click', () => { form.reset(); resourceRoot.querySelector('[data-campaign-fields]').classList.toggle('hidden', resource !== 'campaigns'); resourceRoot.querySelector('[data-automation-fields]').classList.toggle('hidden', resource !== 'automations'); dialog.showModal(); });
    resourceRoot.querySelectorAll('[data-resource-close]').forEach((button) => button.addEventListener('click', () => dialog.close()));
    resourceRoot.querySelector('[data-resource-retry]').addEventListener('click', load);
    form.addEventListener('submit', async (event) => { event.preventDefault(); try { const data = Object.fromEntries(new FormData(form)); if (resource === 'campaigns') { data.html_content = data.html_content || '<p>Conteúdo da campanha</p>'; data.subject = data.subject || data.name; data.recipients = {}; data.idempotency_key = crypto.randomUUID(); } else { data.actions = JSON.parse(data.actions || '[]'); data.active = true; } const response = await fetch(`${resourceRoot.dataset.apiBase}/${endpoint}`, { method: 'POST', headers: { 'Content-Type': 'application/json', Accept: 'application/json' }, body: JSON.stringify(data) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.message || Object.values(payload.errors || {}).flat()[0] || 'Não foi possível salvar.'); form.reset(); dialog.close(); feedback('Registro criado.'); load(); } catch (error) { const target = resourceRoot.querySelector('[data-resource-form-error]'); target.textContent = error.message; target.classList.remove('hidden'); } });
    load();
}
