const settingsRoot = document.querySelector('[data-crm-settings]');

if (settingsRoot) {
    const endpoint = settingsRoot.dataset.endpoint;
    const base = settingsRoot.dataset.apiBase;
    const dialog = settingsRoot.querySelector('[data-settings-dialog]');
    const form = settingsRoot.querySelector('[data-settings-form]');
    const formTitle = settingsRoot.querySelector('[data-settings-form-title]');
    const formSubmit = settingsRoot.querySelector('[data-settings-submit]');
    let stageDraft = [];
    let draggedStageIndex = null;
    let editingPipelineId = null;
    let pipelineRows = [];

    const escapeHtml = (value) => String(value ?? '').replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[character]);
    const show = (name) => settingsRoot.querySelectorAll('[data-settings-state]').forEach((element) => element.classList.toggle('hidden', element.dataset.settingsState !== name));
    const feedback = (message, tone = 'success') => { const target = settingsRoot.querySelector('[data-settings-feedback]'); target.className = `mt-8 rounded-lg p-3 text-sm ${tone === 'error' ? 'bg-red-50 text-red-700' : 'bg-emerald-50 text-emerald-700'}`; target.textContent = message; target.classList.remove('hidden'); };
    const renderRows = (rows) => rows.length ? rows.map((row) => `<article class="px-5 py-4"><div class="flex items-start justify-between gap-4"><div><h2 class="font-semibold text-slate-800">${escapeHtml(row.name || `Registro #${row.id}`)}</h2>${endpoint === 'pipelines' ? `<p class="mt-1 text-sm text-slate-500">${row.stages?.length || 0} ${(row.stages?.length || 0) === 1 ? 'etapa configurada' : 'etapas configuradas'}</p><div class="mt-3 flex flex-wrap gap-2">${(row.stages || []).map((stage) => `<span class="rounded-full bg-brand-50 px-3 py-1 text-xs font-semibold text-brand-700">${escapeHtml(stage.name)}</span>`).join('')}</div>` : `<p class="mt-1 text-sm text-slate-500">ID ${row.id}</p>`}</div>${endpoint === 'pipelines' ? `<div class="flex shrink-0 items-center gap-3"><span class="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-700">Ativo</span><div class="flex items-center gap-1"><button type="button" data-pipeline-edit="${row.id}" class="crm-settings-action crm-settings-action-edit">Editar</button><button type="button" data-pipeline-delete="${row.id}" class="crm-settings-action crm-settings-action-delete">Excluir</button></div></div>` : ''}</div></article>`).join('') : '<p class="px-5 py-14 text-center text-slate-500">Nenhum registro encontrado.</p>';
    const load = async () => { show('loading'); try { const response = await fetch(`${base}/${endpoint}`); const payload = await response.json(); if (!response.ok) throw new Error(payload.message || 'Não foi possível carregar.'); pipelineRows = endpoint === 'pipelines' ? (payload.data || []) : []; settingsRoot.querySelector('[data-settings-rows]').innerHTML = renderRows(payload.data || []); show('content'); } catch (error) { settingsRoot.querySelector('[data-settings-error]').textContent = error.message; show('error'); } };
    const stageIcon = (name) => name === 'grip' ? '<svg aria-hidden="true" viewBox="0 0 20 20" fill="currentColor"><circle cx="6" cy="5" r="1.2"/><circle cx="14" cy="5" r="1.2"/><circle cx="6" cy="10" r="1.2"/><circle cx="14" cy="10" r="1.2"/><circle cx="6" cy="15" r="1.2"/><circle cx="14" cy="15" r="1.2"/></svg>' : name === 'up' ? '<svg aria-hidden="true" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.8"><path d="m5 12 5-5 5 5"/></svg>' : '<svg aria-hidden="true" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.8"><path d="m5 8 5 5 5-5"/></svg>';
    const renderStageEditor = () => { const extra = settingsRoot.querySelector('[data-settings-extra]'); extra.innerHTML = `<div class="crm-stage-editor"><div class="flex items-start justify-between gap-4"><div><label class="block text-sm font-semibold text-slate-700">Etapas do funil</label><p class="mt-1 text-xs text-slate-500">Arraste para ordenar o caminho da oportunidade. A primeira etapa é o ponto de entrada.</p></div><span class="crm-stage-editor-count">${stageDraft.length} ${stageDraft.length === 1 ? 'etapa' : 'etapas'}</span></div><div class="mt-4 grid gap-2" data-stage-list role="list" aria-label="Etapas do funil">${stageDraft.map((stage, index) => `<div class="crm-stage-editor-row" data-stage-index="${index}" draggable="true" role="listitem"><button type="button" class="crm-stage-drag-handle" data-stage-drag aria-label="Arrastar etapa ${index + 1}" title="Arraste para reordenar">${stageIcon('grip')}</button><span class="crm-stage-number" aria-hidden="true">${index + 1}</span><input class="crm-stage-input" data-stage-name="${index}" value="${escapeHtml(stage.name)}" maxlength="160" aria-label="Nome da etapa ${index + 1}" placeholder="Ex.: Qualificação"><div class="crm-stage-row-actions"><button type="button" class="crm-stage-order-button" data-stage-up="${index}" aria-label="Mover etapa para cima" ${index === 0 ? 'disabled' : ''}>${stageIcon('up')}</button><button type="button" class="crm-stage-order-button" data-stage-down="${index}" aria-label="Mover etapa para baixo" ${index === stageDraft.length - 1 ? 'disabled' : ''}>${stageIcon('down')}</button><button type="button" class="crm-stage-remove-button" data-stage-remove="${index}" aria-label="Remover etapa" ${stageDraft.length === 1 ? 'disabled' : ''}>×</button></div></div>`).join('')}</div><button type="button" class="crm-stage-add-button" data-stage-add><span aria-hidden="true">+</span> Adicionar etapa</button><p class="mt-2 text-xs text-slate-500">Você precisa de pelo menos uma etapa.</p></div>`; };
    const addExtraFields = () => { const extra = settingsRoot.querySelector('[data-settings-extra]'); if (endpoint === 'pipelines') { stageDraft = [{ name: 'Novo' }]; renderStageEditor(); } else if (endpoint === 'segments') extra.innerHTML = '<label for="settings-filters" class="mb-1 block text-sm font-semibold text-slate-700">Filtros (JSON)</label><textarea id="settings-filters" name="filters" rows="4" class="w-full rounded-lg border border-slate-300 px-3">{}</textarea>'; else if (endpoint === 'custom-fields') extra.innerHTML = '<div class="grid gap-4 sm:grid-cols-2"><input name="entity" placeholder="Entidade" required class="min-h-11 w-full rounded-lg border border-slate-300 px-3"><input name="type" placeholder="Tipo" required class="min-h-11 w-full rounded-lg border border-slate-300 px-3"></div>'; else extra.innerHTML = ''; };
    const openCreate = () => { editingPipelineId = null; form.reset(); formTitle.textContent = 'Novo funil'; formSubmit.textContent = 'Criar funil'; addExtraFields(); dialog.showModal(); settingsRoot.querySelector('[data-stage-name="0"]')?.focus(); };
    const openEdit = (pipeline) => { editingPipelineId = pipeline.id; form.elements.name.value = pipeline.name; formTitle.textContent = 'Editar funil'; formSubmit.textContent = 'Salvar alterações'; stageDraft = (pipeline.stages || []).map((stage) => ({ id: stage.id, name: stage.name })); renderStageEditor(); dialog.showModal(); settingsRoot.querySelector('[data-stage-name="0"]')?.focus(); };
    const deletePipeline = async (id) => { if (!window.confirm('Excluir este funil? Essa ação não pode ser desfeita.')) return; try { const response = await fetch(`${base}/pipelines/${id}`, { method: 'DELETE', headers: { Accept: 'application/json' } }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.message || 'Não foi possível excluir o funil.'); feedback('Funil excluído.'); load(); } catch (error) { feedback(error.message, 'error'); } };
    const moveStage = (from, to) => { if (to < 0 || to >= stageDraft.length) return; [stageDraft[from], stageDraft[to]] = [stageDraft[to], stageDraft[from]]; renderStageEditor(); settingsRoot.querySelector(`[data-stage-name="${to}"]`)?.focus(); };
    const handleStageEditorClick = (event) => { const target = event.target.closest('button'); if (!target) return; if (target.dataset.pipelineEdit) { const pipeline = pipelineRows.find((row) => row.id === Number(target.dataset.pipelineEdit)); if (pipeline) openEdit(pipeline); } if (target.dataset.pipelineDelete) deletePipeline(target.dataset.pipelineDelete); if (target.matches('[data-stage-add]')) { stageDraft.push({ name: '' }); renderStageEditor(); settingsRoot.querySelector(`[data-stage-name="${stageDraft.length - 1}"]`)?.focus(); } if (target.dataset.stageRemove) { stageDraft.splice(Number(target.dataset.stageRemove), 1); renderStageEditor(); } if (target.dataset.stageUp) moveStage(Number(target.dataset.stageUp), Number(target.dataset.stageUp) - 1); if (target.dataset.stageDown) moveStage(Number(target.dataset.stageDown), Number(target.dataset.stageDown) + 1); };
    const handleStageEditorInput = (event) => { if (event.target.dataset.stageName !== undefined) stageDraft[Number(event.target.dataset.stageName)].name = event.target.value; };
    const handleStageDragStart = (event) => { const row = event.target.closest('[data-stage-index]'); if (!row) return; draggedStageIndex = Number(row.dataset.stageIndex); row.classList.add('crm-stage-editor-row-dragging'); event.dataTransfer.effectAllowed = 'move'; event.dataTransfer.setData('text/plain', row.dataset.stageIndex); };
    const handleStageDragEnd = (event) => { event.target.closest('[data-stage-index]')?.classList.remove('crm-stage-editor-row-dragging'); draggedStageIndex = null; };
    const handleStageDrop = (event) => { const row = event.target.closest('[data-stage-index]'); if (!row || draggedStageIndex === null) return; event.preventDefault(); const targetIndex = Number(row.dataset.stageIndex); if (draggedStageIndex !== targetIndex) { const [stage] = stageDraft.splice(draggedStageIndex, 1); stageDraft.splice(targetIndex, 0, stage); renderStageEditor(); } };
    settingsRoot.querySelector('[data-settings-open]').addEventListener('click', openCreate); settingsRoot.querySelectorAll('[data-settings-close]').forEach((button) => button.addEventListener('click', () => dialog.close())); settingsRoot.querySelector('[data-settings-retry]').addEventListener('click', load);
    settingsRoot.addEventListener('click', handleStageEditorClick); settingsRoot.addEventListener('input', handleStageEditorInput); settingsRoot.addEventListener('dragstart', handleStageDragStart); settingsRoot.addEventListener('dragend', handleStageDragEnd); settingsRoot.addEventListener('dragover', (event) => { if (event.target.closest('[data-stage-index]')) event.preventDefault(); }); settingsRoot.addEventListener('drop', handleStageDrop);
    form.addEventListener('submit', async (event) => { event.preventDefault(); try { const data = Object.fromEntries(new FormData(form)); if (endpoint === 'pipelines') { data.stages = stageDraft.map((stage, position) => ({ ...(stage.id ? { id: stage.id } : {}), name: stage.name.trim(), position })).filter((stage) => stage.name); if (!data.stages.length || data.stages.length !== stageDraft.length) throw new Error('Dê um nome para todas as etapas antes de salvar.'); data.active = true; } if (data.filters) data.filters = JSON.parse(data.filters); const isEditing = endpoint === 'pipelines' && editingPipelineId; const response = await fetch(`${base}/${endpoint}${isEditing ? `/${editingPipelineId}` : ''}`, { method: isEditing ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json', Accept: 'application/json' }, body: JSON.stringify(data) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.message || Object.values(payload.errors || {}).flat()[0] || 'Não foi possível salvar.'); dialog.close(); feedback(isEditing ? 'Funil atualizado com sucesso.' : endpoint === 'pipelines' ? 'Funil criado com sucesso.' : 'Registro criado.'); load(); } catch (error) { const target = settingsRoot.querySelector('[data-settings-form-error]'); target.textContent = error.message; target.classList.remove('hidden'); } });
    load();
}
