<x-layouts.crm title="Agenda" eyebrow="Execução">
    <section class="mx-auto max-w-[1200px] px-4 py-8 sm:px-6 lg:px-8" data-crm-calendar data-api-base="{{ $crmApiBase }}">
        <div class="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-bold uppercase tracking-[0.14em] text-accent-600">Execução</p><h1 class="mt-2 text-3xl font-bold tracking-tight text-slate-900">Agenda</h1><p class="mt-3 max-w-2xl text-base text-slate-500">Veja compromissos do mês e mantenha os próximos encontros no radar.</p></div><button type="button" data-calendar-open-form class="inline-flex min-h-11 items-center justify-center rounded-lg bg-slate-900 px-5 text-sm font-bold text-white transition hover:-translate-y-0.5 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-brand-500 focus:ring-offset-2">+ Novo evento</button></div>
        <div class="mt-8 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><label class="text-sm font-semibold text-slate-700" for="calendar-month">Mês exibido</label><input id="calendar-month" type="month" data-calendar-month class="min-h-11 rounded-lg border border-slate-300 bg-white px-3 text-sm outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-100"></div>
        <div class="mt-4 hidden" data-calendar-feedback role="status"></div>
        <div class="mt-4" data-calendar-state="loading" aria-busy="true" aria-label="Carregando agenda"><div class="h-64 animate-pulse rounded-2xl border border-slate-200 bg-slate-100"></div></div>
        <div class="mt-4 hidden" data-calendar-state="error" role="alert"><div class="rounded-2xl border border-red-200 bg-red-50 p-6 text-red-800"><h2 class="font-bold">Não foi possível carregar a agenda</h2><p class="mt-2 text-sm" data-calendar-error></p><button type="button" data-calendar-retry class="mt-4 rounded-lg bg-red-700 px-4 py-2 text-sm font-bold text-white hover:bg-red-800">Tentar novamente</button></div></div>
        <div class="mt-4 hidden" data-calendar-state="content"><div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[0_5px_10px_rgba(2,2,76,0.02)]"><div class="divide-y divide-slate-100" data-calendar-events></div></div></div>
        <dialog data-calendar-dialog class="w-[min(100%-2rem,34rem)] rounded-2xl border border-slate-200 p-0 shadow-2xl backdrop:bg-slate-900/30"><form method="dialog" data-calendar-form class="p-6 sm:p-8"><div class="flex items-start justify-between gap-4"><div><p class="crm-kicker">Registro</p><h2 data-calendar-form-title class="mt-1 text-xl font-bold text-slate-900">Adicionar evento</h2></div><button type="button" data-calendar-close aria-label="Fechar formulário" class="rounded-lg p-2 text-xl leading-none text-slate-500 hover:bg-slate-100">×</button></div><div class="mt-6 grid gap-4"><div><label for="calendar-title" class="mb-1 block text-sm font-semibold text-slate-700">Título <span class="text-red-600">*</span></label><input id="calendar-title" name="title" required maxlength="180" class="min-h-11 w-full rounded-lg border border-slate-300 px-3 outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-100"></div><div class="grid gap-4 sm:grid-cols-2"><div><label for="calendar-start" class="mb-1 block text-sm font-semibold text-slate-700">Início</label><input id="calendar-start" name="start_at" type="datetime-local" required class="min-h-11 w-full rounded-lg border border-slate-300 px-3 outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-100"></div><div><label for="calendar-end" class="mb-1 block text-sm font-semibold text-slate-700">Fim</label><input id="calendar-end" name="end_at" type="datetime-local" required class="min-h-11 w-full rounded-lg border border-slate-300 px-3 outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-100"></div></div><label class="flex items-center gap-2 text-sm font-semibold text-slate-700"><input name="all_day" type="checkbox" value="1" class="h-4 w-4 rounded border-slate-300 text-brand-600"> Evento de dia inteiro</label><div><label for="calendar-notes" class="mb-1 block text-sm font-semibold text-slate-700">Observações</label><textarea id="calendar-notes" name="notes" rows="3" class="w-full rounded-lg border border-slate-300 px-3 py-2 outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-100"></textarea></div></div><p class="mt-4 hidden rounded-lg bg-red-50 p-3 text-sm text-red-700" data-calendar-form-error role="alert"></p><div class="mt-7 flex justify-end gap-3"><button type="button" data-calendar-close class="rounded-lg border border-slate-200 px-4 py-2.5 text-sm font-bold text-slate-600 hover:bg-slate-50">Cancelar</button><button type="submit" data-calendar-submit class="rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-bold text-white hover:bg-slate-700">Salvar evento</button></div></form></dialog>
    </section>
</x-layouts.crm>
