<x-layouts.crm title="Contatos" eyebrow="Relacionamento">
    <section class="mx-auto max-w-[1440px] px-4 py-8 sm:px-6 lg:px-8" data-crm-contacts data-api-base="{{ $crmApiBase }}">
        <div class="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between">
            <div><p class="text-sm font-bold uppercase tracking-[0.14em] text-accent-600">Relacionamento</p><h1 class="mt-2 text-3xl font-bold tracking-tight text-slate-900">Contatos</h1><p class="mt-3 max-w-2xl text-base text-slate-500">Encontre pessoas, consulte seus dados e mantenha o próximo contato sempre visível.</p></div>
            <button type="button" data-contact-open-form class="inline-flex min-h-11 items-center justify-center rounded-lg bg-slate-900 px-5 text-sm font-bold text-white transition hover:-translate-y-0.5 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-brand-500 focus:ring-offset-2">+ Novo contato</button>
        </div>

        <div class="mt-8 rounded-2xl border border-slate-200 bg-white p-4 shadow-[0_5px_10px_rgba(2,2,76,0.02)] sm:p-5">
            <form class="flex flex-col gap-3 sm:flex-row" data-contact-search>
                <label class="sr-only" for="contact-search">Buscar contatos</label>
                <input id="contact-search" name="search" type="search" placeholder="Buscar por nome ou e-mail" class="min-h-11 flex-1 rounded-lg border border-slate-300 px-4 text-sm outline-none transition placeholder:text-slate-400 focus:border-brand-500 focus:ring-2 focus:ring-brand-100">
                <button type="submit" class="min-h-11 rounded-lg border border-slate-300 px-5 text-sm font-bold text-slate-700 hover:border-brand-300 hover:bg-brand-50 hover:text-brand-700">Buscar</button>
            </form>
        </div>

        <div class="mt-4 hidden" data-contact-feedback role="status"></div>
        <div class="mt-4" data-contact-list-state="loading" aria-busy="true" aria-label="Carregando contatos"><div class="h-64 animate-pulse rounded-2xl border border-slate-200 bg-slate-100"></div></div>
        <div class="mt-4 hidden" data-contact-list-state="error" role="alert"><div class="rounded-2xl border border-red-200 bg-red-50 p-6 text-red-800"><h2 class="font-bold">Não foi possível carregar os contatos</h2><p class="mt-2 text-sm" data-contact-error></p><button type="button" data-contact-retry class="mt-4 rounded-lg bg-red-700 px-4 py-2 text-sm font-bold text-white hover:bg-red-800">Tentar novamente</button></div></div>
        <div class="mt-4 hidden" data-contact-list-state="content">
            <div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[0_5px_10px_rgba(2,2,76,0.02)]">
                <div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><caption class="sr-only">Lista de contatos</caption><thead class="border-b border-slate-200 bg-slate-50 text-xs uppercase tracking-[0.08em] text-slate-500"><tr><th scope="col" class="px-5 py-4 font-bold">Nome</th><th scope="col" class="px-5 py-4 font-bold">E-mail</th><th scope="col" class="px-5 py-4 font-bold">Telefone</th><th scope="col" class="px-5 py-4 font-bold">Empresa</th><th scope="col" class="px-5 py-4 text-right font-bold">Ações</th></tr></thead><tbody data-contact-rows class="divide-y divide-slate-100"></tbody></table></div>
                <div class="flex flex-col gap-3 border-t border-slate-100 px-5 py-4 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between"><span data-contact-summary></span><div class="flex gap-2"><button type="button" data-contact-prev class="rounded-lg border border-slate-200 px-3 py-2 font-semibold hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-40">Anterior</button><button type="button" data-contact-next class="rounded-lg border border-slate-200 px-3 py-2 font-semibold hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-40">Próxima</button></div></div>
            </div>
        </div>

        <dialog data-contact-dialog class="w-[min(100%-2rem,32rem)] rounded-2xl border border-slate-200 p-0 shadow-2xl backdrop:bg-slate-900/30"><form method="dialog" data-contact-form class="p-6 sm:p-8"><div class="flex items-start justify-between gap-4"><div><p class="crm-kicker">Registro</p><h2 class="mt-1 text-xl font-bold text-slate-900" data-contact-form-title>Adicionar contato</h2></div><button type="button" data-contact-close aria-label="Fechar formulário" class="rounded-lg p-2 text-xl leading-none text-slate-500 hover:bg-slate-100">×</button></div><div class="mt-6 grid gap-4"><div><label for="contact-first-name" class="mb-1 block text-sm font-semibold text-slate-700">Nome <span class="text-red-600">*</span></label><input id="contact-first-name" name="first_name" required maxlength="120" class="min-h-11 w-full rounded-lg border border-slate-300 px-3 outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-100"></div><div><label for="contact-last-name" class="mb-1 block text-sm font-semibold text-slate-700">Sobrenome</label><input id="contact-last-name" name="last_name" maxlength="120" class="min-h-11 w-full rounded-lg border border-slate-300 px-3 outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-100"></div><div><label for="contact-email" class="mb-1 block text-sm font-semibold text-slate-700">E-mail</label><input id="contact-email" name="email" type="email" maxlength="255" class="min-h-11 w-full rounded-lg border border-slate-300 px-3 outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-100"></div><div><label for="contact-phone" class="mb-1 block text-sm font-semibold text-slate-700">Telefone</label><input id="contact-phone" name="phone" maxlength="40" class="min-h-11 w-full rounded-lg border border-slate-300 px-3 outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-100"></div></div><p class="mt-4 hidden rounded-lg bg-red-50 p-3 text-sm text-red-700" data-contact-form-error role="alert"></p><div class="mt-7 flex justify-end gap-3"><button type="button" data-contact-close class="rounded-lg border border-slate-200 px-4 py-2.5 text-sm font-bold text-slate-600 hover:bg-slate-50">Cancelar</button><button type="submit" data-contact-submit class="rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-bold text-white hover:bg-slate-700">Salvar contato</button></div></form></dialog>
    </section>
</x-layouts.crm>
