<x-layouts.crm title="Oportunidades e pipeline" eyebrow="Vendas">
    <section class="mx-auto max-w-[1440px] px-4 py-8 sm:px-6 lg:px-8" data-crm-pipeline-page data-api-base="{{ $crmApiBase }}">
        <div class="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-bold uppercase tracking-[0.14em] text-accent-600">Vendas</p><h1 class="mt-2 text-3xl font-bold tracking-tight text-slate-900">Oportunidades e pipeline</h1><p class="mt-3 max-w-2xl text-base text-slate-500">Veja onde cada negócio está e mantenha o próximo movimento claro para o time.</p></div><div class="flex gap-2"><button type="button" data-pipeline-refresh class="inline-flex min-h-11 items-center justify-center rounded-lg border border-slate-300 px-5 text-sm font-bold text-slate-700 hover:border-brand-300 hover:bg-brand-50 hover:text-brand-700">Atualizar quadro</button><button type="button" data-opportunity-open-form class="inline-flex min-h-11 items-center justify-center rounded-lg bg-slate-900 px-5 text-sm font-bold text-white hover:bg-slate-700">+ Oportunidade</button></div></div>
        <div class="mt-8 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><label class="text-sm font-semibold text-slate-700" for="pipeline-select">Funil exibido</label><select id="pipeline-select" data-pipeline-select class="min-h-11 rounded-lg border border-slate-300 bg-white px-3 text-sm outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-100"><option>Carregando funis...</option></select></div>
        <div class="mt-4 hidden" data-pipeline-feedback role="status"></div>
        <div class="mt-4" data-pipeline-state="loading" aria-busy="true" aria-label="Carregando pipeline"><div class="grid gap-3 md:grid-cols-2 xl:grid-cols-4">@foreach (range(1, 4) as $skeleton)<div class="h-64 animate-pulse rounded-2xl border border-slate-200 bg-slate-100" aria-hidden="true"></div>@endforeach</div></div>
        <div class="mt-4 hidden" data-pipeline-state="error" role="alert"><div class="rounded-2xl border border-red-200 bg-red-50 p-6 text-red-800"><h2 class="font-bold">Não foi possível carregar o pipeline</h2><p class="mt-2 text-sm" data-pipeline-error></p><button type="button" data-pipeline-retry class="mt-4 rounded-lg bg-red-700 px-4 py-2 text-sm font-bold text-white hover:bg-red-800">Tentar novamente</button></div></div>
        <div class="mt-4 hidden" data-pipeline-state="content"><div class="overflow-x-auto pb-2"><div class="crm-board" data-pipeline-board></div></div></div>
        <dialog data-opportunity-dialog class="w-[min(100%-2rem,36rem)] rounded-2xl border border-slate-200 p-0 shadow-2xl backdrop:bg-slate-900/30"><form method="dialog" data-opportunity-form class="p-6 sm:p-8"><div class="flex items-start justify-between gap-4"><div><p class="crm-kicker">Vendas</p><h2 class="mt-1 text-xl font-bold text-slate-900" data-opportunity-form-title>Nova oportunidade</h2></div><button type="button" data-opportunity-close aria-label="Fechar formulário" class="rounded-lg p-2 text-xl leading-none text-slate-500 hover:bg-slate-100">×</button></div><div class="mt-6 grid gap-4"><div><label for="opportunity-title" class="mb-1 block text-sm font-semibold text-slate-700">Título <span class="text-red-600">*</span></label><input id="opportunity-title" name="title" required maxlength="180" class="min-h-11 w-full rounded-lg border border-slate-300 px-3"></div><div class="grid gap-4 sm:grid-cols-2"><div><label for="opportunity-contact" class="mb-1 block text-sm font-semibold text-slate-700">Contato <span class="text-red-600">*</span></label><select id="opportunity-contact" name="contact_id" required class="min-h-11 w-full rounded-lg border border-slate-300 bg-white px-3"><option value="">Selecione</option></select></div><div><label for="opportunity-company" class="mb-1 block text-sm font-semibold text-slate-700">Empresa</label><select id="opportunity-company" name="company_id" class="min-h-11 w-full rounded-lg border border-slate-300 bg-white px-3"><option value="">Nenhuma</option></select></div></div><div class="grid gap-4 sm:grid-cols-2"><div><label for="opportunity-stage" class="mb-1 block text-sm font-semibold text-slate-700">Etapa <span class="text-red-600">*</span></label><select id="opportunity-stage" name="pipeline_stage_id" required class="min-h-11 w-full rounded-lg border border-slate-300 bg-white px-3"></select></div><div><label for="opportunity-amount" class="mb-1 block text-sm font-semibold text-slate-700">Valor</label><input id="opportunity-amount" name="amount" type="number" min="0" step="0.01" class="min-h-11 w-full rounded-lg border border-slate-300 px-3"></div></div><div><label for="opportunity-currency" class="mb-1 block text-sm font-semibold text-slate-700">Moeda</label><input id="opportunity-currency" name="currency" value="BRL" maxlength="3" class="min-h-11 w-full rounded-lg border border-slate-300 px-3 uppercase"></div></div><p class="mt-4 hidden rounded-lg bg-red-50 p-3 text-sm text-red-700" data-opportunity-form-error role="alert"></p><div class="mt-7 flex justify-end gap-3"><button type="button" data-opportunity-close class="rounded-lg border border-slate-200 px-4 py-2.5 text-sm font-bold text-slate-600">Cancelar</button><button type="submit" data-opportunity-submit class="rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-bold text-white">Salvar oportunidade</button></div></form></dialog>
    </section>
</x-layouts.crm>
