<x-layouts.crm title="Tarefas" eyebrow="Execução">
    <section class="mx-auto max-w-[1440px] px-4 py-8 sm:px-6 lg:px-8" data-crm-tasks-page data-api-base="{{ $crmApiBase }}">
        <div class="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-bold uppercase tracking-[0.14em] text-accent-600">Execução</p><h1 class="mt-2 text-3xl font-bold tracking-tight text-slate-900">Tarefas</h1><p class="mt-3 max-w-2xl text-base text-slate-500">Organize os próximos passos e marque o que foi concluído sem sair do fluxo.</p></div><button type="button" data-task-open-form class="inline-flex min-h-11 items-center justify-center rounded-lg bg-slate-900 px-5 text-sm font-bold text-white transition hover:-translate-y-0.5 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-brand-500 focus:ring-offset-2">+ Nova tarefa</button></div>
        <div class="mt-8 flex flex-wrap gap-2" role="tablist" aria-label="Filtros de tarefas"><button type="button" data-task-scope="upcoming" class="crm-filter-button crm-filter-button-active">Próximas</button><button type="button" data-task-scope="today" class="crm-filter-button">Hoje</button><button type="button" data-task-scope="overdue" class="crm-filter-button">Atrasadas</button><button type="button" data-task-scope="all" class="crm-filter-button">Todas</button></div>
        <div class="mt-4 hidden" data-task-feedback role="status"></div>
        <div class="mt-4" data-task-state="loading" aria-busy="true" aria-label="Carregando tarefas"><div class="h-64 animate-pulse rounded-2xl border border-slate-200 bg-slate-100"></div></div>
        <div class="mt-4 hidden" data-task-state="error" role="alert"><div class="rounded-2xl border border-red-200 bg-red-50 p-6 text-red-800"><h2 class="font-bold">Não foi possível carregar as tarefas</h2><p class="mt-2 text-sm" data-task-error></p><button type="button" data-task-retry class="mt-4 rounded-lg bg-red-700 px-4 py-2 text-sm font-bold text-white hover:bg-red-800">Tentar novamente</button></div></div>
        <div class="mt-4 hidden" data-task-state="content"><div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[0_5px_10px_rgba(2,2,76,0.02)]"><div class="divide-y divide-slate-100" data-task-rows></div><div class="flex flex-col gap-3 border-t border-slate-100 px-5 py-4 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between"><span data-task-summary></span><div class="flex gap-2"><button type="button" data-task-prev class="rounded-lg border border-slate-200 px-3 py-2 font-semibold hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-40">Anterior</button><button type="button" data-task-next class="rounded-lg border border-slate-200 px-3 py-2 font-semibold hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-40">Próxima</button></div></div></div></div>
        <dialog data-task-dialog class="w-[min(100%-2rem,32rem)] rounded-2xl border border-slate-200 p-0 shadow-2xl backdrop:bg-slate-900/30"><form method="dialog" data-task-form class="p-6 sm:p-8"><div class="flex items-start justify-between gap-4"><div><p class="crm-kicker">Registro</p><h2 data-task-form-title class="mt-1 text-xl font-bold text-slate-900">Adicionar tarefa</h2></div><button type="button" data-task-close aria-label="Fechar formulário" class="rounded-lg p-2 text-xl leading-none text-slate-500 hover:bg-slate-100">×</button></div><div class="mt-6 grid gap-4"><div><label for="task-title" class="mb-1 block text-sm font-semibold text-slate-700">Título <span class="text-red-600">*</span></label><input id="task-title" name="title" required maxlength="180" class="min-h-11 w-full rounded-lg border border-slate-300 px-3 outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-100"></div><div class="grid gap-4 sm:grid-cols-2"><div><label for="task-due-at" class="mb-1 block text-sm font-semibold text-slate-700">Prazo</label><input id="task-due-at" name="due_at" type="datetime-local" class="min-h-11 w-full rounded-lg border border-slate-300 px-3 outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-100"></div><div><label for="task-priority" class="mb-1 block text-sm font-semibold text-slate-700">Prioridade</label><select id="task-priority" name="priority" class="min-h-11 w-full rounded-lg border border-slate-300 bg-white px-3 outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-100"><option value="normal">Normal</option><option value="low">Baixa</option><option value="high">Alta</option><option value="urgent">Urgente</option></select></div></div><div><label for="task-notes" class="mb-1 block text-sm font-semibold text-slate-700">Observações</label><textarea id="task-notes" name="notes" rows="3" class="w-full rounded-lg border border-slate-300 px-3 py-2 outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-100"></textarea></div></div><p class="mt-4 hidden rounded-lg bg-red-50 p-3 text-sm text-red-700" data-task-form-error role="alert"></p><div class="mt-7 flex justify-end gap-3"><button type="button" data-task-close class="rounded-lg border border-slate-200 px-4 py-2.5 text-sm font-bold text-slate-600 hover:bg-slate-50">Cancelar</button><button type="submit" data-task-submit class="rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-bold text-white hover:bg-slate-700">Salvar tarefa</button></div></form></dialog>
    </section>
</x-layouts.crm>
